POST http://localhost:3001/api/linkedinJobs
Content-Type: application/json

{
    "keyword": "Web Developer",
    "location": "Surrey, British Columbia, Canada",
    "postedTime": "Any time",
    "distance": null,
    "commute": "Remote, Hybrid",
    "company": null,
    "salary": null,
    "jobType": "Full-time",
    "experienceLevel": "Entry level",
    "include": [],
    "exclude": ["years of professional experience"],
    "applied": ["Code Particle Inc"]
}